default: &default
  adapter: postgresql
  username: <%= ENV["DB_USER"] %> 
  password: <%= ENV["APP_DATABASE_PASSWORD"] %> 
  port: <%= ENV["APP_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blogdos_development 

test:
  <<: *default
  database: blogdos_test 

production:
  <<: *default
  database: blogdos_production 
